# Generated by Django 5.0.3 on 2024-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_developer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
